
# Arranca el subsistema cuando se inicia el contexto principal de Alfresco.
alfresco.alfdockia.subsystem.autoStart=true

# Arranca los contenedores registrados cuando se inicia el subsistema.
alfresco.alfdockia.subsystem.startAgentsOnStart=true

# Detiene los contenedores registrados cuando se detiene el subsistema.
alfresco.alfdockia.subsystem.stopAgentsOnStop=true

# Tiempo maximo que Docker esperara antes de forzar la parada del contenedor.
alfresco.alfdockia.subsystem.stopTimeoutSeconds=10
